@ECHO OFF
FOR %%D IN (TYP2.EXE TYP2.COM  TYP2.OBJ) DO IF EXIST %%D DEL %%D
SET ERW=COM
ALP TYP2.ALP
LINK386 TYP2.OBJ,TYP2.%ERW%,NUL.MAP,,TYP2.DEF
rem CALL LXLITE TYP2.%ERW% /f+ /zs /T:\V\STUB\STUB.EXE
CALL LXLITE TYP2.%ERW% /f+ /zs
