vpart.cfg wird auch von TEST.COM ver„ndert ?
.def/.eds
Erzeugen eines Ordners auf der Arbeitsoberfl„che
  * Dokumentation
  * Installation (cmd)
  * Installationseinstellungen
  * icon_gal

gen_vk

ntfs ist wie fat32 ?


BIN-Datei
(*datendatei:----------

'VPart * Veit Kannegieser * 2001.03.12',13,10,27

Kennung berprfen

anzahl_bl”cke
  beschreinungsl„nge
  dateiposition
  laenge_eingepackt
  laenge_ausgepackt
  dateiname

gross(dateiname)
 Pos('.512',dateiname)
 -----------------------*)
