@ECHO OFF
CALL PASVP BUS_SEKT .\ /U.. /I..
BUS_SEKT.EXE
DEL BUS_SEKT.EXE
IF EXIST SEKT__16.OBJ DEL SEKT__16.OBJ
IF EXIST SEKT__32.OBJ DEL SEKT__32.OBJ
BINOBJ32                     SEKT.DAT SEKT__32.OBJ SEKT_BUSCH
START /B /C C:\BP\BIN\BINOBJ SEKT.DAT SEKT__16.OBJ SEKT_BUSCH
rem DEL SEKT.DAT