@ECHO OFF
CALL PASVP BUS_EXE0 .\ /U.. /I..
BUS_EXE0.EXE
DEL BUS_EXE0.EXE
IF EXIST EXE___16.OBJ DEL EXE___16.OBJ
IF EXIST EXE___32.OBJ DEL EXE___32.OBJ
BINOBJ32                     EXE.DAT EXE___32.OBJ EXE_BUSCH
START /B /C C:\BP\BIN\BINOBJ EXE.DAT EXE___16.OBJ EXE_BUSCH
rem DEL EXE.DAT