even 010
;***************************************************************************

int_21_org:
int_21_org_o		dw ?
int_21_org_s		dw ?

int_21_neu:
			pushf
			  cmp ah,064
			  jnz weiter
			  
			  cmp cx,0636c
			  jnz weiter
			  
			  ;cmp bh,01
			  ;jnz weiter
			  
			  int 3
			
weiter:
			popf
			jmp d cs:[int_21_org]
tsr_ende:

;***************************************************************************
