@ECHO OFF
REM %TYP%=Verzeichnis fÅr TemporÑre Dateien
SET TYP=%TMP%\1
IF [%TYP%]==[] GOTO ENDE
MD %TYP%

ECHO Lîschen alter Dateien ...
FOR %%D IN (%TYP%\*.*) DO DEL %%D
IF EXIST TYP.VK\TYP4.EXE    DEL TYP.VK\TYP4.EXE
IF EXIST TYP.VK\TYPEIN4.EXE DEL TYP.VK\TYPEIN4.EXE

ECHO Datumsdatei ...
CALL ..\TTMMJJ\TTMMJJ.EXE /PAS TYPDATUM.PAS

ECHO Compiler + Linker ...
CALL PASVPWlf TYP     %TYP%\ -I.\INC_W32 -I%TYP% -O%TYP% @TYP.CFG
CALL PASVPWlf TYPEIN  %TYP%\ -I.\INC_W32 -I%TYP% -O%TYP% @TYPEIN.CFG

ECHO Kopieren
COPY %TYP%\TYP.EXE    TYP.VK\TYP4.EXE
COPY %TYP%\TYPEIN.EXE TYP.VK\TYPEIN4.EXE

FOR %%D IN (%TYP%\*.*) DO DEL %%D
RD %TYP%

:ENDE
