(*$Define TYP_EXE*)
(*$I TYP_COMP.PAS*)
program datei_typ_hauptprogramm;
(*$D Typ * Dateitypbestimmung / Archivlistprogramm * V.K.*)

(* 26.12.1993 nach a.exe *)

(*$IfDef Win32*)
(*$R typ4.res*)
(*$EndIf Win32*)

(*$IfDef VirtualPascal*)
  (*$PMTYPE VIO*)
(*$EndIf VirtualPascal*)

uses
  (*heapchk,*)
  (*memleaks,*)

  (*$IfDef DPMI32*)
    (*$IfNDef ENDVERSION*)
      deb_link,
    (*$EndIf ENDVERSION*)
  (*$EndIf DPMI32*)

  typ_haup;

(*$IfDef DOS_OVERLAY*)
  (* O DOS     *) (* unklar *)
  (* O Overlay *)
  (* O OverXMS *)
  (*$O NTAB    *)
  (* O SPR2_AUS*)
  (* O Strings *)
  (* O System  *)
  (* O TpSysLow*)
  (* O TYP_AUSG*) (* zu oft benutzt *)
  (*$O TYP_BIOS*)
  (*$O TYP_BOOT*)
  (*$O TYP_C2E *)
  (*$O TYP_CD  *)
  (* O TYP_DAT *) (* zu langsam/zu groá *)
  (* O TYP_DAT1*) (* zu langsam/zu groá *)
  (* O TYP_DAT2*) (* zu langsam/zu groá *)
  (*$O TYP_DATX*)
  (*$O TYP_DESC*)
  (*$O TYP_DIE2*)
  (*$O TYP_DIE3*)
  (*$O TYP_DIEN*)
  (*$O TYP_EAS *)
  (* O TYP_EIAU*) (* ? *)
  (* O TYP_EING*) (* ? *)
  (*$O TYP_ENDE*)
  (*$O TYP_ENTP*)
  (*$IfDef ERWEITERUNGSDATEI*)
  (*$O TYP_ERW *)
  (*$EndIf ERWEITERUNGSDATEI*)
  (* O TYP_EXE0*) (* ? *)
  (* O TYP_EXE1*) (* ? *)
  (* O TYP_EXE2*) (* ? *)
  (*$O TYP_FOR0*)
  (*$O TYP_FOR1*)
  (*$O TYP_FOR2*)
  (*$O TYP_FOR3*)
  (*$O TYP_FOR4*)
  (*$O TYP_FOR5*)
  (* O TYP_GT  *) (* sowiso nicht auf 286 *)
  (*$O TYP_HAUP*)
  (*$O TYP_HILF*)
  (*$O TYP_KOPF*)
  (*$O TYP_NETW*)
  (*$O TYP_OS  *)
  (* O TYP_OVR *) (* darf nicht *)
  (*$O TYP_PARA*)
  (*$O TYP_POEM*)
  (*$O TYP_POLY*)
  (*$O TYP_POSM*)
  (*$O TYP_SEKT*)
  (*$O TYP_SPEI*)
  (* O TYP_SPRA*) (* darf nicht  *)
  (* O TYP_SPRU*) (* lohnt nicht *)
  (* O TYP_TAKT*) (* lohnt nicht *)
  (*$O TYP_TYPE*)
  (* O TYP_VAR *) (* wird h„ufig benutzt *)
  (* O TYP_VARX*) (* wird h„ufig benutzt *)
  (*$O TYP_XEXE*)
  (*$O TYP_ZEIC*)
  (* O UniDef  *) (* sinnlos *)
  (* O UTF8    *) (* geht nicht *)
  (*$O WinDos  *)
  (*$O ZST     *)
  (* O ZST_OBJ *) (* ? *)
  (*$O ZTAB    *)

(*$EndIf DOS_OVERLAY*)

begin
  EXE_HAUPTPROGRAMMAUFRUF;
end.

