(* detect Turbo Pascal *)
(*$IfDef MSDOS*)
  (*$Define DOS*)
(*$EndIf*)

(*$IfDef DOS*)
  (* stabil aber Speichermangel+Geschwindigkeitsnachteil *)
  (*$Define DOS_OVERLAY*)
  (*$Define DOS_ODER_DPMI*)
  (*$Define DOS_ODER_DPMI_ODER_DPMI32*)
(*$EndIf*)

(*$IfDef DPMI*)
  (* stÑndig dabei abzustÅrzen *)
  (*$Define DOS_ODER_DPMI*)
  (*$Define DOS_ODER_DPMI_ODER_DPMI32*)
(*$EndIf*)

(*$IfDef DPMI32*)
  (* volle LauffÑhigkeit *)
  (*$Define DOS_ODER_DPMI_ODER_DPMI32*)
(*$EndIf*)

(*$IfDef Linux*)
  (* ungetestet *)
  (*$Define LNX*)
  (*$Define LNX_ODER_W32*)
(*$EndIf*)

(*$IfDef OS2*)
  (* volle LauffÑhigkeit *)
(*$EndIf*)

(*$IfDef Win32*)
  (* ungetestet *)
  (*$Define W32*)
  (*$Define LNX_ODER_W32*)
(*$EndIf*)


(* solution for using DPMI32 variables in TP compiled SETUP program *)
(*$IfNDef TYP_DOS*)
  (*$IfNDef TYP_OS2*)
    (*$IfNDef TYP_DPMI32*)
      (*$IfNDef TYP_DPMI*)
        (*$IfNDef TYP_LNX*)
          (*$IfNDef TYP_W32*)

            (*$IfDef DOS*)
              (*$Define TYP_DOS*)
            (*$EndIf*)

            (*$IfDef DPMI*)
              (*$Define TYP_DPMI*)
              (*$Define DOS_ODER_DPMI*)
            (*$EndIf*)

            (*$IfDef DPMI32*)
              (*$Define TYP_DPMI32*)
            (*$EndIf*)

            (*$IfDef Linux*)
              (*$Define TYP_LNX*)
            (*$EndIf*)

            (*$IfDef OS2*)
              (*$Define TYP_OS2*)
            (*$EndIf*)

            (*$IfDef Win32*)
              (*$Define TYP_W32*)
            (*$EndIf*)

          (*$EndIf*)
        (*$EndIf*)
      (*$EndIf*)
    (*$EndIf*)
  (*$EndIf*)
(*$EndIf*)



(*  $Define ENDVERSION*)
(*  $Define PROFILER*)
(*  $Define BILDWIEDERHOLRATE*)
(*  $Define PRUEFE_TAKT*)

(*$IfDef VirtualPascal*)
  (*  $Define SPEICHER_FREIGEBEN*)
  (*$Define KEINE_SEGMENTE*)
(*$EndIf*)


(*$IfDef TYP_DOS*)
  (*$Define TERM_ROLLEN*)
  (*$Define TERM_FARBIG*)
(*$EndIf*)

(*$IfDef TYP_DPMI*)
  (*$Define TERM_ROLLEN*)
  (*$Define TERM_FARBIG*)
(*$EndIf*)

(*$IfDef TYP_DPMI32*)
  (*$Define TERM_ROLLEN*)
  (*$Define TERM_FARBIG*)
  (*$Define ERWEITERUNGSDATEI*)
  (*$Define TYP_VP*)
(*$EndIf*)

(*$IfDef TYP_LNX*)
  (*$Define TERM_FARBIG*)
  (*$Define ERWEITERUNGSDATEI*)
  (*$Define TYP_VP*)
(*$EndIf*)

(*$IfDef TYP_OS2*)
  (*$Define TERM_ROLLEN*)
  (*$Define TERM_FARBIG*)
  (*$Define ERWEITERUNGSDATEI*)
  (*$Define TYP_VP*)
(*$EndIf*)

(*$IfDef TYP_W32*)
  (*$Define TERM_FARBIG*)
  (*$Define ERWEITERUNGSDATEI*)
  (*$Define TYP_VP*)
(*$EndIf*)

(*$A+*) (* geradzahlige ADR *)
(*$B-*) (* Kurzschlu·logik *)
(*$E-*) (* ohne Emulator *)
(*$F-*) (* nicht zwingend far *)
(*$G+*) (* 80286+ *)
(*$I+*) (* FehlerpfrÅfung *)

(* Speicherbedarf: siehe typ_ovr
   ZST_OBJ/ZTAB benîtigt 8*124+... *)


(*$IfDef DOS*)
  (*$IfDef TYP_EXE*)
    (*$IfDef DOS_OVERLAY*)
      (*$M 50000,2000,240000*) (* lieber mit /BA arbeiten als stÑndig das Overlay nachladen *)
    (*$Else*)
      (*$M 50000,2000,0*) (* TYP_SPEI.PAS: zur Zeit kein NEW(..) von 16KB *)
    (*$EndIf*)
  (*$Else*)
    (*$M 50000,2000,2000*)
  (*$EndIf*)
(*$EndIf*)


(*$IfDef DPMI*)
  (*$M 60000*)
(*$EndIf*)

(*$IfDef OS2*)
  (*$IfDef TYP_EXE*)
    (*$M 800000*)
  (*$Else*)
    (*$M 40000*)
  (*$EndIf*)
(*$EndIf*)

(*$IfDef DPMI32*)
  (*$IfDef TYP_EXE*)
    (*$M 800000*)
  (*$Else*)
    (*$M 40000*)
  (*$EndIf*)
(*$EndIf*)

(*$IfDef VirtualPascal*)

  (*$Define GTDATA*)

  (*$AlignCode+*)
  (*$AlignData+*)
  (*   $AlignCode-*)
  (*   $AlignData-*)
  (*$AlignRec-*)
  (*$Asm-*)
  (*$Delphi+*)
  (*$Frame+*)        (* Geschwindigkeitseinbu·e *)
  (*$G3+*)
  (*$LocInfo+*)      (* nur fÅr D+ *)
  (*$OrgName-*)      (* Åbersichtlicher .LIB *)
  (*$P-*)            (* normale Bedeutung von "string" *)
  (*$Speed+*)
  (*$Z-*)            (* AufzÑhlungstypen -> 1 byte *)
  (*$Zd-*)           (* keine Zeileninfo fÅr externen Debugger *)
  (*$Use32-*)

  (*$IfDef VER20*)
  (*$H-*)            (* Ansistring *)
  (*$J+*)            (* Typisierte Komstanten = initaliesierte Variablen *)
  (*$M-*)            (* Typinfo wÑhrend der Laufzeit *)
  (*$Open32-*)       (* keine Resourcen *)
  (*$Use32-*)        (* alte integer/word-Typen *)
  (*$EndIf*)
(*$EndIf*)

(*$N-*) (* ohne xxx87 *)
(*$O-*) (* kein Overlay als Grundeinstellung *)
(*$P-*) (* keine offenen Felder *)
(*$Q-*) (* mit öberlÑufen kommt das Programm so klar *)
(*$T+*) (* strenge ZeigerprÅfung ein *)
(*$V+*) (* Strenge TypprÅfung ein *)
(*$X+*) (* erweiterter Syntax *)
(*$Y-*) (* Symbolerzeugung aus *)

(*$IfDef ENDVERSION*)
  (*$IfDef VirtualPascal*)
    (*$SmartLink+*)
    (*$OPTIMIZE+*)
    (*$LocInfo-*)
    (*$W-*)
  (*$EndIf*)
  (*$D-*) (* Debug aus *)
  (*$L-*) (* Debug aus *)
  (*$R-*) (* BereichsÅberprÅfung aus *)
  (*$S-*) (* StackÅberprÅfung aus *)
(*$Else*)
  (*$IfDef VirtualPascal*)
    (*$SmartLink-*)
    (*$Optimise-*)
    (*$LocInfo+*)
    (*$W+*)
  (*$EndIf*)
  (*$D+*) (* Debug zum Testen ein *)
  (*$L+*) (* Debug zum Testen ein *)
  (*$R+*) (* BereichsÅberprÅfung ein *)
  (*$S+*) (* StackÅberprÅfung ein *)
  (*$Y+*)
(*$EndIf*)

(*$IfNDef ENDVERSION*)
  (*$IfDef DOS*)
    (*$IfNDef DOS_OVERLAY*)
      (*$Define HILFE_EINSPAREN*)
    (*$EndIf*)
  (*$EndIf*)
(*$EndIf*)

(*$IfDef VirtualPascal*)
  (*$Define dateigroessetyp_comp*)
(*$EndIf*)

