Title   english language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "Menu configurazione OS/2 "

; install.inc

msg_install_aborted             equ <"Installazione interrotta.",13,10>
msg_Using_reserved_memory       equ <"Utilizzo della memoria riservata.",13,10>
msg_Using_video_memory          equ <"Utilizzo della memoria video.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Caricamento OS2LDR in corso ... "
err_os2boot1                    equ "Versione OS2BOOT sconosciuta <1>"
err_os2boot2                    equ "Versione OS2BOOT sconosciuta <2>"
err_os2boot3                    equ "Versione OS2BOOT sconosciuta <3>"
err_cannot_open_os2ldr_bin      equ "Errore nell'apertura del file OS2LDR.BIN !"
err_read_error_                 equ "Errore di lettura !"

; mod.inc

msg_yes_no                      equ " (S/No) ? "
key_yes                         equ "s"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " อออออออออออออออออออออออออ[premere un tasto per continuare]ออออออออออออออออออออ"
