Title   dutch language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "OS/2 Configuratie Menu "

; install.inc

msg_install_aborted             equ <"Installatie afgebroken.",13,10>
msg_Using_reserved_memory       equ <"Gebruik gereserveerd geheugen.",13,10>
msg_Using_video_memory          equ <"Gebruik video geheugen.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Laden OS2LDR ... "
err_os2boot1                    equ "Onbekende OS2BOOT versie <1>"
err_os2boot2                    equ "Onbekende OS2BOOT versie <2>"
err_os2boot3                    equ "Onbekende OS2BOOT versie <3>"
err_cannot_open_os2ldr_bin      equ "Fout bij openen OS2LDR.BIN bestand !"
err_read_error_                 equ "Leesfout !"

; mod.inc

msg_yes_no                      equ " (Ja/Nee) ? "
key_yes                         equ "j"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " 様様様様様様様様様様様様[druk een toets om verder te gaan]様様様様様様様様様様"

