Title   german language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "OS/2 Config Men "

; install.inc

msg_install_aborted             equ <"Installation abgebrochen.",13,10>
msg_Using_reserved_memory       equ <"Benutze reservierten Speicher.",13,10>
msg_Using_video_memory          equ <"Benutze Bildschirmspeicher.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Lade OS2LDR ... "
err_os2boot1                    equ "OS2BOOT ist unbekannt <1>"
err_os2boot2                    equ "OS2BOOT ist unbekannt <2>"
err_os2boot3                    equ "OS2BOOT ist unbekannt <3>"
err_cannot_open_os2ldr_bin      equ "Fehler beim ffnen von OS2LDR.BIN !"
err_read_error_                 equ "Lesefehler !"

; mod.inc

msg_yes_no                      equ " (Ja/Nein) ? "
key_yes                         equ "j"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " อออออออออออออออออออออออออออออ[weiter mit Tastendruck]อออออออออออออออออออออออออ"

