Title   espaniol language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "OS/2 Config Menu "

; install.inc

msg_install_aborted             equ <"Instalaciขn abortada.",13,10> ; &oacute;
msg_Using_reserved_memory       equ <"Utilizando memoria reservada.",13,10>
msg_Using_video_memory          equ <"Utilizando memoria de video.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Cargando OS2LDR ... "
err_os2boot1                    equ "Versiขn <1> de OS2BOOT desconocida" ; &oacute;
err_os2boot2                    equ "Versiขn <2> de OS2BOOT desconocida"
err_os2boot3                    equ "Versiขn <3> de OS2BOOT desconocida"
err_cannot_open_os2ldr_bin      equ "Error al abrir el archivo OS2LDR.BIN !"
err_read_error_                 equ "Error de lectura !"

; mod.inc

msg_yes_no                      equ " (Sก/No) ? " ; &iacute;
key_yes                         equ "s"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " ออออออออออออออออออออออออออออออ[Pulse cualquier tecla]อออออออออออออออออออออออออ"
