Title   english language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "OS/2 Config Menu "

; install.inc

msg_install_aborted             equ <"Install aborted.",13,10>
msg_Using_reserved_memory       equ <"Using reserved memory.",13,10>
msg_Using_video_memory          equ <"Using video memory.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Loading OS2LDR ... "
err_os2boot1                    equ "Unknown OS2BOOT version <1>"
err_os2boot2                    equ "Unknown OS2BOOT version <2>"
err_os2boot3                    equ "Unknown OS2BOOT version <3>"
err_cannot_open_os2ldr_bin      equ "Error opening file OS2LDR.BIN !"
err_read_error_                 equ "Read error !"

; mod.inc

msg_yes_no                      equ " (Yes/No) ? "
key_yes                         equ "y"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " ออออออออออออออออออออออออออออออ[press key to continue]อออออออออออออออออออออออออ"
