Title   french language dependant strings for OS2CSM

; datum.inc

msg_title                       equ "Menu de config. OS/2  "

; install.inc

msg_install_aborted             equ <"Installation interrompue.",13,10>
msg_Using_reserved_memory       equ <"Utilisation de la mmoire rserve.",13,10>
msg_Using_video_memory          equ <"Utilisation de la mmoire video.",13,10>

; lader.inc
msg_Loading_OS2LDR__            equ "Chargement de OS2LDR ... "
err_os2boot1                    equ "Version inconnue de OS2BOOT <1>"
err_os2boot2                    equ "Version inconnue de OS2BOOT <2>"
err_os2boot3                    equ "Version inconnue de OS2BOOT <3>"
err_cannot_open_os2ldr_bin      equ "Erreur … l'ouverture de OS2LDR.BIN !"
err_read_error_                 equ "Erreur de lecture !"

; mod.inc

msg_yes_no                      equ " (Oui/Non) ? "
key_yes                         equ "o"
key_no                          equ "n"

                                ;   "*******************************************************************************"
msg_key_to_continue             equ " ออออออออออออออออออออ[Appuyer sur une touche pour continuer]อออออออออออออออออออ"

