Title    automaticly generated keyboard remap table (dutch: nl 143)

keyboard_title equ "dutch: nl 143"

keytable_remapscan:
  db 0

keytable_Lower:
  db 00Ch,'/'
  db 00Dh,'ø'
  db 01Ah,'ù'
  db 01Bh,'*'
  db 027h,'+'
  db 028h,'ï'
  db 029h,'@'
  db 02Bh,'<'
  db 035h,'-'
  db 056h,']'
  db 0

keytable_Upper:
  db 003h,'"'
  db 007h,'&'
  db 008h,'_'
  db 009h,'('
  db 00Ah,')'
  db 00Bh,027h
  db 00Ch,'?'
  db 00Dh,'~'
  db 01Ah,'^'
  db 01Bh,'|'
  db 027h,'ñ'
  db 028h,'`'
  db 029h,'õ'
  db 02Bh,'>'
  db 033h,';'
  db 034h,':'
  db 035h,'='
  db 056h,'['
  db 0

keytable_AltGr:
  db 002h,'û'
  db 003h,'ý'
  db 004h,'ü'
  db 005h,'¬'
  db 006h,'«'
  db 007h,'ó'
  db 008h,'œ'
  db 009h,'{'
  db 00Ah,'}'
  db 00Ch,'\'
  db 012h,'Õ'
  db 013h,'ô'
  db 01Fh,'á'
  db 029h,'ª'
  db 02Ch,'®'
  db 02Dh,'¯'
  db 02Eh,'½'
  db 032h,'æ'
  db 033h,'['
  db 034h,'ú'
  db 035h,']'
  db 056h,'Ý'
  db 0

keytable_Alt:
  db 0

keytable_Ctrl:
  db 0

