Title    automaticly generated keyboard remap table (russian: ru 441 or 443)

keyboard_title equ "russian: ru 441 or 443"

keytable_remapscan:
  db 0

keytable_Lower:
  db 0

keytable_Upper:
  db 0

keytable_AltGr:
  db 002h,'!'
  db 003h,'"'
  db 004h,'¸'
  db 005h,';'
  db 006h,':'
  db 007h,','
  db 009h,'*'
  db 00Ah,'('
  db 00Bh,')'
  db 00Ch,'-'
  db 00Dh,'='
  db 010h,'â'
  db 011h,'ñ'
  db 012h,'ì'
  db 013h,'ä'
  db 014h,'Ö'
  db 015h,'ç'
  db 016h,'É'
  db 017h,'ò'
  db 018h,'ô'
  db 019h,'á'
  db 01Ah,'ï'
  db 01Bh,'ö'
  db 01Eh,'î'
  db 01Fh,'õ'
  db 020h,'Ç'
  db 021h,'Ä'
  db 022h,'è'
  db 023h,'ê'
  db 024h,'é'
  db 025h,'ã'
  db 026h,'Ñ'
  db 027h,'Ü'
  db 028h,'ù'
  db 029h,027h
  db 02Bh,'\'
  db 02Ch,'ü'
  db 02Dh,'ó'
  db 02Eh,'ë'
  db 02Fh,'å'
  db 030h,'à'
  db 031h,'í'
  db 032h,'ú'
  db 033h,'Å'
  db 034h,'û'
  db 035h,''
  db 056h,'\'
  db 0

keytable_Alt:
  db 0

keytable_Ctrl:
  db 0

